### ISSUE TITLE
modifications toward pps/allostatic for WYSIWYD

### ISSUE THREAD

**Issue by matejhof** [robotology/peripersonal-space#13]
modifications needed: 
 * [x] visuoTactileWrapper
   * [x] new input modality - reading multiple object coordinates from 
`/objectGeneratorSim/obstacles:o` `(x1 y1 z1 RADIUS) (x2 y2 z2 RADIUS) … (xn yn zn RADIUS)`
   * [x] output - modify /visuoTactileWrapper/events:o to stream multiple objects - e.g. 
`(pos_x pos_y pos_z vel_x vel_y vel_z object_radius source_of_info)` (SAME FOR SECOND OBJECT)
 * [x] visuoTactileRF
   * [x] needs to sum up activations from multiple objects (assuming only additive now - all objects as threats)
   * [x] output - modify `/visuoTactileRF/skin_events:o` to send multiple (avoidance) vectors - meaning maximum 1 per skin part

**Comment by alecive** [comment]
What a nice issue report! The only thing that was missing were the code tags where needed (I already did that :+1: )

**Comment by pattacini** [comment]
Seems we can close this.
Reopen if needed.
