### ISSUE TITLE
visuoTactileRF segfaults after start

### ISSUE THREAD

**Issue by matejhof** [robotology/peripersonal-space#16]
[feature/WYSIWYD branch] It seems to segfault soon after the start - I tried couple of options, icub, icubSim, 1D, 2D, but always same.

**Comment by alecive** [comment]
Can you paste me the terminal output?

**Comment by matejhof** [comment]
``./visuoTactileRF: Symbol `_ZTVN4yarp3sig10VectorBaseE' has different size in shared object, consider re-linking
[INFO]Module name set to visuoTactileRF
[INFO]Robot is icub
[INFO]Could not find modality option in the config file; using 1D as default
[INFO]vtRFThread verbosity set to 0
[INFO]vtRFThread working at  100 ms
[INFO]SKIN_EVENTS section found
[INFO][skin_event] filePath [0] /usr/local/share/iCub/contexts/skinGui/positions/left_hand_V2_1.txt
[INFO][skin_event] filePath [1] /usr/local/share/iCub/contexts/skinGui/positions/left_forearm_mesh.txt
[INFO][skin_event] filePath [2] /usr/local/share/iCub/contexts/skinGui/positions/right_hand_V2_1.txt
[INFO][skin_event] filePath [3] /usr/local/share/iCub/contexts/skinGui/positions/right_forearm_mesh.txt
Segmentation fault (core dumped)``

**Comment by alecive** [comment]
can you run it with some more verbosity? Also, you should recompile I think (as the first line of code is suggesting).
