### ISSUE TITLE
adapt code to be compatible with icub v2 skin

### ISSUE THREAD

**Issue by matejhof** [robotology/peripersonal-space#17]
On the blackie, there are forearms and hands V2 as of December 2015. There are differences in the skin. Most importantly, the upper patch on forearm has 8 rather than 7 triangles. For the rest, need to check whether the positions differ. For sure, appropriate new taxel pos files need to be loaded correctly. The representative taxel code - to pick triangle centers - also needs to be checked.
This also means that our old learned datasets are not really useful for the blackie anymore. 
Bluey still has forearms V1.

**Comment by alecive** [comment]
Completely unrelated: so the blackie has been upgraded with the new forearms? Hooray!! I did a full Phd in the meanwhile but happy to know they arrived at some point :D

**Comment by matejhof** [comment]
We still need to tackle this one day. Just explained to Phuong Ngyuen @towardthesea what this is about.... This would involve creating a new positions file under `icub-main/app/skinGui/conf/positions`, e.g. left_forearm_V2.txt, including the mapping to the representative taxels for the additional triangle on the upper part of forearm. Then checking if that is enough for PPS to pick it up automatically....

**Comment by traversaro** [comment]
@matejhof Yesterday I brefly introduced @towardthesea to the work (terribly undocumented : ( ) that we did to generate a `torso.txt` configuration file `icub-main/app/skinGui/conf/positions` starting from 2D triangle positions and CAD data in https://github.com/robotology-playground/icub-taxel-positions . 

We could look into cleaning up the procedure to produce taxel positions even for the forearm v2.

**Comment by matejhof** [comment]
Just to help to clarify where we stand from the pps software perspective.
The pps software is internally relying on forearm V1 skin and hand_V2_1 skin. When visualizing on corresponding `skinGuis`, it looks like this: 

![ppsv1activationsonv1skingui](https://cloud.githubusercontent.com/assets/6461061/17935250
/e250cad6-6a1a-11e6-9a97-9c3e9573fef3.png)

(Need to check - it seems the right palm taxels at the thumb are ignored.)
This version of guis can also be used to visualize the PPS representations learned previously with V1 arm iCub, such as these: [learned_all.ini](https://github.com/robotology/peripersonal-space/blob/master/app/conf/taxels1D_learnedAll.ini).

Blindly sending the forearm V1-like activations to V2 forearm `skinGuis` gives this:
![ppsv1activationsonv2skingui](https://cloud.githubusercontent.com/assets/6461061/17935257/e9573018-6a1a-11e6-8188-d4937c93414c.png)
This shows where the differences are (the upper patch now has 8 instead of 7 triangles; plus the order somehow changes).
Now, if we want to do any new learning of the PPS using the V2 forearm skin, we need to:

1.  allow  for that in the PPS software
2. do the forearm skin calibration to obtain new taxel positions files

So, yes @traversaro , let's do that!

**Comment by matejhof** [comment]
N.B. During start of `visuoTactileRF` module, the files to retrieve taxel positions are taken from [skinManForearms.ini](https://github.com/robotology/icub-main/blob/master/app/skinGui/conf/skinManForearms.ini). Once positions files for V2 forearms are available and if the robot is configured correctly, they will be automatically taken from there.

**Comment by matejhof** [comment]
This part will have to be modified to comply with V2 forearm skin: https://github.com/robotology/peripersonal-space/blob/pps-with-modulations/modules/visuoTactileRF/vtRFThread.cpp#L1202

**Comment by matejhof** [comment]
The asymmetry in the palm representative taxels was here: https://github.com/robotology/peripersonal-space/blob/pps-with-modulations/modules/visuoTactileRF/vtRFThread.cpp#L1260
Enabling all of them in current branch (`pps-with-modulations-dev`) - even the region around the thumb of right hand for completeness (699d4753a2f96d9deeb30ef8a277d593190b8824).

**Comment by alecive** [comment]
Nice you found it out! Probably we decided to remove it for some reason during the experiments :+1:

**Comment by matejhof** [comment]
This has been completed now and tested. Most of the implementation is in this commit: 
c7f397eb87231bf8e9b25ad11fcd3878dae7a5a8
The new code is so far in the `pps-with-modulations-dev-V2skinAndkinematics` branch. To be merged into 'pps-with-modulations` after resolving also #30.
Can be reopened if problems pop up - for example after @towardthesea visualizes what we just learned on the robot.

**Comment by matejhof** [comment]
also the `virtualContactGeneration` module was updated with V2 skin option.
here: 2e8939294b2e548cde442c32d04f8bb2e3bac622
