### ISSUE TITLE
OpenCV-3.x.y compatibility

### ISSUE THREAD

**Issue by vicentepedro** [robotology/peripersonal-space#19]
Hi all!

I tried to compile the repository using OpenCV 3.x.y.

I got the usual errors due to the conversion from IplImage to Mat using the constructor method.

I don't know if you want to support it. ;)

**Comment by pattacini** [comment]
Hi @vicentepedro 
Thanks for spotting.
I and @alecive will be soon on this upgrade.

**Comment by pattacini** [comment]
@alecive @matejhof 
Concerning this overhaul, we have to first merge the feature branch into master and soon afterwards proceed with the upgrade to opencv-3.x.y.

**Comment by matejhof** [comment]
For now, I discovered that it seems it is only the fingertipTracker module with this problem. That one is not necessary for the core functionality, so we can just comment its compilation out.

**Comment by pattacini** [comment]
See #21.

**Comment by pattacini** [comment]
Should be fixed.

**Comment by alecive** [comment]
@vicentepedro now it is fixed only in the `feature/WYSIWYD` branch, but as soon as #20 is fixed, also the master branch will be up-to-date with OpenCV 3.*

**Comment by pattacini** [comment]
For the #20, @alecive could you do that? :smile:.

**Comment by alecive** [comment]
I'm waiting for @matejhof to come back from the review meeting because I can merge remotely but I cannot test it :stuck_out_tongue:

**Comment by pattacini** [comment]
You could do already the first two bullet points though.

**Comment by pattacini** [comment]
@vicentepedro @alecive 
Unlike I said before, I first fixed the opencv related issues. This was because only `fingertipTracker ` was affected.

**Comment by alecive** [comment]
@vicentepedro now the `feature/WYSIWID` branch has been merged onto `master`, and the code should be OpenCV 3.* compatible. Please report back if you still have any issues!
