### ISSUE TITLE
allowing for bounding boxes, not just circular incoming events (obstacles)

### ISSUE THREAD

**Issue by matejhof** [robotology/peripersonal-space#22]
For the scenario we are developing with @towardthesea and @pattacini  - "reaching in clutter" - we are leveraging on the `IOL` output that gives us 3d bounding boxes of objects in the scene. We want to transform this output into something similar to what was sent from `visuoTactileWrapper/events:o` to `visuoTactileRF/events:i`, which looks like this (for `pf3dTracker` case and 1 object):
  * `(x_pos y_pos z_pos  x_vel y_vel z_vel radius pf3dTracker)`

What we have in mind is something like:
  * `(x_pos y_pos z_pos  x_vel y_vel z_vel  {radius/boundingBox}Tag x_dim/radius y_dim z_dim  pf3dTracker)`

So we can fork on whether it is a round object or a box using a tag, for example? Or for simplicity we assume everything is a box, including red ball? ;)

We also definitely need multiple objects - so it could be simply a sequence of such bottles. Or preceded by a number of objects to read? I think the `visuoTactileRF` is already supporting reading multiple objects/events [here](https://github.com/robotology/peripersonal-space/blob/master/modules/visuoTactileRF/vtRFThread.cpp#L290). 

It could be done in a separate module or maybe the visuoTactileWrapper could be extended to take next to `pf3dTracker` and `ultimateTracker`, the `IOL` input format onboard.

In any case, the output of the Wrapper / new module (and input to `visuoTactileRF`) needs to accommodate also bounding box format. One way is to extend the `IncomingEvent` struct I suppose ([here](https://github.com/robotology/peripersonal-space/blob/master/lib/include/iCub/periPersonalSpace/utils.h#L84)).

In addition to `visuoTactileRF`, a planning module of @towardthesea would be another recipient of this information. 
What you think @alecive ?

**Comment by alecive** [comment]
Can you please be more clear on what you would like to go? 

I cannot understand this (x_pos y_pos z_pos x_vel y_vel z_vel {radius/boundingBox}Tag x_dim/radius y_dim z_dim pf3dTracker)

Further, the branch feature/WSYWID was devised specifically for multiple objects.

In any case, yes, the `visuoTactileWrapper` is exactly made for this purpose of wrapping anything might be useful in a format that is suitable for the `vtRF`.

**Comment by matejhof** [comment]
We need to allow for the option of having a bounding box or radius for every object - one option is that that would be signalled by a tag. The other option is that radius will be replaced by bounding box even for spheres.

Yes, feature/WYSIWYD should be able to handle that - even though we never tested I think.

So yes, we could modify the visuoTactileWrapper accordingly (and utils.h)?

For the IOL input, we won't have velocities, but we can put zeros.

I guess this features should be added after the merge of branches?

**Comment by alecive** [comment]
The third option (that makes more sense to me) is that the bounding box is replaced by a radius. It makes more sense because you don't disrupt everything else with minor damage.

The radius is used internally to compute the minimum distance between the object and the taxel (i.e. the one we care about), which is kind of difficult with a bounding box. I would stick with the radius of the sphere that is circumscribed into the bounding box (or inscribed).

Why do you plan on changing `utils.h`?

**Comment by matejhof** [comment]
Hmm, I did not think it all through. Maybe yes. The thing is that we'd like to take into account the full occupancy of obstacles - approximating a bottle with an inscribed sphere will be a massive underestimation of its dimension / circumscribed will be an overestimation. The planner of @towardthesea can deal with full bounding boxes. However, I forgot that PPS cannot and this would require a major extension. 
So perhaps for now, @towardthesea  can read the bounding boxes from the IOL directly, whereas in PPS we could extend the Wrapper to read from IOL and do the gross circular approximation.

**Comment by alecive** [comment]
Yes agreed. Further, the extension would also require the orientation of the box in 3D, not only its size.

**Comment by pattacini** [comment]
@matejhof could you please edit your original post above and apply markdown formatting properly?
The text is very barely readable.

**Formatting, formatting, everywhere vigorously and rigorously**.
I'm starting off bothering you heavily from now on :wink:.

**Comment by pattacini** [comment]
Actually, I'm really tempted to close this issue straightaway and force you all to be clean...

**Comment by matejhof** [comment]
Hi there, ok formatting of original message somewhat improved. 
As for the solution, we keep the existing format of the message and I will extend `visuoTactileWrapper` to extract bounding boxes from `IOL` and transform them into circular objects with position (their center) and radius as first approximation.
Later, if there are elongated objects for which the inscribed/circumscribed sphere would be a too coarse approximation, we can think of using multiple spheres per bounding box.

**Comment by matejhof** [comment]
Let's close this one for now and reopen when needed. We have other burning issues.
