### ISSUE TITLE
considering torso joints when projecting stimuli onto taxel frames

### ISSUE THREAD

**Issue by matejhof** [robotology/peripersonal-space#26]
Currently, the PPS software was not taking the torso joints into account and while projecting external stimuli onto the taxel frames, it was assuming the torso is in home. 
https://github.com/robotology/peripersonal-space/blob/pps-with-modulations/modules/visuoTactileRF/vtRFThread.cpp#L835
What needs to be done:

 * [ ] unlock the torso in `armL` and `armR` 
 * [x] create a new encoder for reading the torso joints

**Comment by matejhof** [comment]
actually, torso encoders seem to be already in place: https://github.com/robotology/peripersonal-space/blob/pps-with-modulations/modules/visuoTactileRF/vtRFThread.cpp#L194

**Comment by alecive** [comment]
It is used for projecting the taxel into the eyes (something that I did long ago but we rarely used afterwards). So even better! There's less work to do :)

**Comment by matejhof** [comment]
Ok, but still we need to free the joints in the iCubArms, here? 
https://github.com/robotology/peripersonal-space/blob/pps-with-modulations/modules/visuoTactileRF/vtRFThread.cpp#L37
Something like: 
  ```for (int i = 0; i < NR_TORSO_JOINTS; i++)
  {
        armL->releaseLink(i);
        armR->releaseLink(i);
   }```
We don't need an option without the torso, do we?

**Comment by alecive** [comment]
I don't think so, but I would release the left and right arms separately because we should account for when one of the two arms is not available and we want to use the other one. I would put the two `for` loops inside the already available `if`s: https://github.com/robotology/peripersonal-space/blob/pps-with-modulations/modules/visuoTactileRF/vtRFThread.cpp#L112

**Comment by matejhof** [comment]
Should be addressed by this commit: 0eb263263225dc5c336c6efa181b2501e51b74f2 
in `pps-with-modulations-dev`
Will test before closing. 
@alecive check the commit if you want.

**Comment by alecive** [comment]
Shall we open the pull request that fixes this issue?

**Comment by matejhof** [comment]
Solved by accepting current pull request of `pps-with-modulation-dev` into `pps-with-modulation`.
