### ISSUE TITLE
add option for iCub V2 arm kinematics

### ISSUE THREAD

**Issue by matejhof** [robotology/peripersonal-space#30]
This is related to https://github.com/robotology/peripersonal-space/issues/17 but also the different kinematics of V2 arms needs to be considered. 
This should probably be added to the .ini file and then the `iCubArm` chains created with the appropriate option. 
What is actually the physical difference?
[Here](https://github.com/robotology/icub-main/blob/master/src/libraries/iKin/src/iKinFwd.cpp#L1757) I also see that `v>1.7` robots have an extra link? 
This would need to be carefully taken into account in places like [this](https://github.com/robotology/peripersonal-space/blob/pps-with-modulations-devMultiEvent/modules/visuoTactileRF/vtRFThread.cpp#L920) where the skin references frames are retrieved.
@pattacini what do you think?

**Comment by pattacini** [comment]
Hi @matejhof 

There's no extra link: you might have not realized that there are no curly brackets.
For the rest, yep, of course, the correct kinematics should be taken into account within `PPS`.

**Comment by alecive** [comment]
So if there is no new link, also this one should be closed?

**Comment by matejhof** [comment]
There's no extra link, but the dimensions are different, so needs to be considered.

**Comment by matejhof** [comment]
@towardthesea, maybe you could have a look at this with the help of @pattacini , such that after that is solved we could merge the `pps-with-modulations-dev-V2skinAndKinematics` branch into `pps-with-modulations`?

**Comment by matejhof** [comment]
@towardthesea could you have a look perhaps, so we can then do a PR for this branch?

**Comment by pattacini** [comment]
Good idea indeed

**Comment by towardthesea** [comment]
@matejhof what should I pay attention on during the testing?

**Comment by matejhof** [comment]
The change in kinematics is small, but we should figure out how to test it - probably through printouts of some taxel pos. I will give pointers where in the PPS code to make the changes. In the meantime, please figure our with the help of @pattacini how to get the right info - which kinematics version - from the robot conf. files.

In addition, I just realized the `virtualContactGeneration` module should also be modified accordingly - similarly to what has been done here: https://github.com/robotology/peripersonal-space/issues/17
I'll try to take care of that one.

**Comment by matejhof** [comment]
ok, let' try to address this asap, so we can merge and move on.
@pattacini, could you please point to an example how this is done correctly in one of the existing modules (Cart. control for example I guess)? I assume, the robot version should be retrieved from local conf. files and based on that we can handle it in the code.

**Comment by pattacini** [comment]
@matejhof what are we speaking about here?

#### Configuration files of the robot?
Then, the skin should be configured properly in the robot directory hosted at [robots-configuration](https://github.com/robotology/robots-configuration) repository. Just put therein the correct xml files. You shouldn't need to specify the skin version anywhere, I suppose.

I am not aware of any automatic way the skin can use to make this info available through queries via ports at run-time (as done e.g. with `iKinGazeCtrl`). Perhaps @traversaro can give us heads-up on this.

#### Configuration files of user modules?
Just put the option in the configuration file exported from the module context.

**Comment by pattacini** [comment]
`iKinGazeCtrl` does exactly this.

**Comment by matejhof** [comment]
Implemented, using the `--arm_version` parameter, accepting a double: {1.0,1.7,2.0} are the possible options. Defaults are V1 kinematics for `icubSim`, V2 for `icub`.
Relevant commits:
c6ee46a5037f7958134c91cf576094eef976ca1c
4b06d148d881cb18577f4c23d2d638fb69baca8c

Closing.
(Exporting `visuoTactileRF.ini` with robot configuration remains as an option for the future.)
