### ISSUE TITLE
Youtube video

### ISSUE THREAD

**Issue by pattacini** [robotology/peripersonal-space#7]
Publish the video on the icub youtube channel and update the link within the paper.

**Comment by matejhof** [comment]
after publication I would say?

**Comment by pattacini** [comment]
yep

**Comment by alecive** [comment]
Done. Video available here (when it will be processed):

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/hVQginjCTC0/0.jpg)](http://www.youtube.com/watch?v=hVQginjCTC0)

**Comment by alecive** [comment]
Previous video was not working. This one is working:

[![peripersonal space video](http://img.youtube.com/vi/3IaXxNwC_7E/0.jpg)](http://www.youtube.com/watch?v=3IaXxNwC_7E)

I updated the `README.md` accordingly.
